export const connectorsComponent = [
  { name: 'Fusion', key: 'fusion', image: 'test.com/img2.png' },
  { name: 'Aria', key: 'aria', image: 'test.com/img3.png' },
  { name: 'Alot System ', key: 'alot', image: 'test.com/img4.png' },
];

export const bankAccounts = [
  { name: 'Bank1', id: 123 },
  { name: 'Bank2', id: 456 },
];

export const paymentMethods = [
  { name: 'Cash1', id: 123 },
  { name: 'Cash2', id: 456 },
];

export const products = [
  { name: 'T-shirt', id: 123 },
  { name: 'Book1', id: 456 },
];

export const taxCodes = [
  { name: 'GST 1.5%', id: 1, percentage: 1.5 },
  { name: 'GST 2.5%', id: 2, percentage: 2.5 },
];

export const transactionStats = [
  {
    type: 'Not_Synced',
    count: 100,
  },
  {
    type: 'Synced',
    count: 200,
  },
  {
    type: 'Error',
    count: 10,
  },
  {
    type: 'Ignored',
    count: 12,
  },
  {
    type: 'Removed',
    count: 100,
  },
];

export const accounts = [
  {
    name: 'Nexus Infotech',
    region: 'USA',
    id: 1,
    status: 'Active',
    limits: {
      total: 100,
      used: 90,
      left: 10,
    },
    selected: false,
  },
  {
    name: 'Nexus Infotech',
    region: 'Europe',
    id: 2,
    status: 'Non-Active',
    limits: {
      total: 100,
      used: 90,
      left: 10,
    },
    selected: false,
  },
  {
    name: 'Nexus Infotech',
    region: 'India',
    id: 3,
    status: 'Non-Active',
    limits: {
      total: 100,
      used: 90,
      left: 10,
    },
    selected: false,
  },
  {
    name: 'Opt Software',
    region: 'Europe',
    id: 4,
    status: 'Non-Active',
    limits: {
      total: 100,
      used: 90,
      left: 10,
    },
    selected: false,
  },
  {
    name: 'Opt Software',
    region: 'India',
    id: 5,
    status: 'Non-Active',
    limits: {
      total: 100,
      used: 90,
      left: 10,
    },
    selected: false,
  },
];
export const transactions = {
  page: 1,
  total: 19,
  start: 1,
  end: 10,
  pageCount: 10,
  data: [
    {
      id: 1,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 2,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 3,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 4,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 5,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 6,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 7,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 8,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 9,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 10,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 11,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 12,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 13,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 14,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 15,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 16,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 17,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 18,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
    {
      id: 19,
      transactionDate: '13/10/2018',
      type: 'Express Checkout',
      contact: 'Customer 1',
      processor: 'paypal',
      total: 100,
      currency: 'USD',
      status: 'paid',
      link: 'https://paypal.com/data/1234',
    },
  ],
};
