export const ON_BOARDING = 'ON_BOARDING';

export const FETCH_CONNECTORS = 'FETCH_CONNECTORS';
export const FETCHING_CONNECTORS = 'FETCHING_CONNECTORS';
export const SUCCESS_FETCHING_CONNECTORS = 'SUCCESS_FETCHING_CONNECTORS';
export const FAILED_FETCHING_CONNECTORS = 'FAILED_FETCHING_CONNECTORS';

// Preferences
export const FETCH_PREFERENCES = 'FETCH_PREFERENCES';
export const FETCHING_PREFERENCES = 'FETCHING_PREFERENCES';
export const SUCCESS_FETCHING_PREFERENCES = 'SUCCESS_FETCHING_PREFERENCES';
export const FAILED_FETCHING_PREFERENCES = 'FAILED_FETCHING_PREFERENCES';

// Transaction Stats
export const FETCH_TRANSACTION_STATS = 'FETCH_TRANSACTION_STATS';
export const FETCHING_TRANSACTION_STATS = 'FETCHING_TRANSACTION_STATS';
export const SUCCESS_FETCHING_TRANSACTION_STATS =
  'SUCCESS_FETCHING_TRANSACTION_STATS';
export const FAILED_FETCHING_TRANSACTION_STATS =
  'FAILED_FETCHING_TRANSACTION_STATS';

// Transactions
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCHING_TRANSACTIONS = 'FETCHING_TRANSACTIONS';
export const SUCCESS_FETCHING_TRANSACTIONS = 'SUCCESS_FETCHING_TRANSACTIONS';
export const FAILED_FETCHING_TRANSACTIONS = 'FAILED_FETCHING_TRANSACTIONS';

// Accounts
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const FETCHING_ACCOUNTS = 'FETCHING_ACCOUNTS';
export const SUCCESS_FETCHING_ACCOUNTS = 'SUCCESS_FETCHING_ACCOUNTS';
export const FAILED_FETCHING_ACCOUNTS = 'FAILED_FETCHING_ACCOUNTS';
