export const data = [
  {
    id: 1,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 2,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 3,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 4,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 5,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 6,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 7,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 8,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 9,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 10,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 11,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 12,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 13,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 14,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 15,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 16,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 17,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 18,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
  {
    id: 19,
    transactionDate: '13/10/2018',
    type: 'Express Checkout',
    contact: 'Customer 1',
    processor: 'paypal',
    total: 100,
    currency: 'USD',
    status: 'paid',
    link: 'https://paypal.com/data/1234',
  },
];
